### ISSUE TITLE
OAuth Setup in README is misleading

### ISSUE THREAD

**Issue by CHH** [prismicio/SymfonyBundle#18]
The README describes an OAuth setup for previewing upcoming releases. But there isn't a class `Prismic\Bundle\PrismicBundle\Controller\OAuthController` in the bundle.

**Comment by erwan** [comment]
Thanks for the report - OAuth is actually deprecated, we have a simpler way to preview documents now:

https://blog.prismic.io/VGTPsyQAACQAqzsZ/preview-content-changes-in-your-website

**Comment by CHH** [comment]
Already using that :smile:, but didn't know about the preview bar. Awesome!
