### ISSUE TITLE
Incompatibility since upgrade to PHP7.0

### ISSUE THREAD

**Issue by nanocom** [prismicio/SymfonyBundle#22]
Hi,

I upgraded to PHP7.0 and there is no apcu backwards compatibility on this version, so we need the latest version of the SDK(~2.0) in this bundle to make it work (apcu_\* functions).

**Comment by erwan** [comment]
Thank you for the report, I'll upgrade the kit in the bundle.

**Comment by thomasglachant** [comment]
@erwan any update about the upgrade ?
