### ISSUE TITLE
Symfony3 compatiblity?

### ISSUE THREAD

**Issue by nanocom** [prismicio/SymfonyBundle#23]
Is there any plan to make this bundle compatible with Symfony3?

**Comment by erwan** [comment]
Yes, we'll migrate it to Symfony3 eventually.

If you're in a hurry to use it in Symfony3, don't hesitate to make a PR!

**Comment by nanocom** [comment]
I would like to but the php kit depends on phpdocumentor which depends on symfony2 so I would need to make a PR to phpdocumentor first...
Can this dependency be dropped? Is anybody still using this documentation? Seems to me that your online documentation is sufficient.

**Comment by nanocom** [comment]
@erwan can you update the php kit version so that everybody can upgrade to symfony 3?

**Comment by srenault** [comment]
Hi @nanocom, I'll see with the team. I'll come back to you ASAP.

**Comment by nanocom** [comment]
I would recommend to deprecate this repo and keep your dev efforts on the php-sdk, providing code examples to integrate prismic on a symfony app in your documentation.

**Comment by srenault** [comment]
I believe this issue has been solved with this commit, right?
https://github.com/prismicio/php-kit/commit/681f328382015c28471199c7115c064cdec1134b#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780.

**Comment by bogdaniel** [comment]
I managed to install the php-sdk but this bundle doesn't want to install :(

**Comment by srenault** [comment]
Okey I'll try to look at it this week!

**Comment by osavchenko** [comment]
Using at least symfony 3.0 will be possible after the php-kit upgrade because the current version depends on `symfony/event-dispatcher` and it makes impossible just to bump symfony version.
